services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "2578:2578"
    volumes:
      - /work_dirs:/mmaction2/work_dirs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "2578", "--workers", "4"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile(nginx)
    ports:
      - "82:82"
    depends_on:
      - app

